fixed java docs and removed unused code
felixbrunnegard/tda367_group15 pull request #22
Opened 2022-10-23 19:09 UTC by Annelie12

2022-10-23 20:17 UTC, felixbrunnegard requested changes

2022-10-23 20:17 UTC, felixbrunnegard commented on src/main/java/com/TDA367group15/app/model/Player.java
> -
Detta ska bort right? Tänkte bara dubbelkolla så du inte råkat ta bort det.

2022-10-23 20:17 UTC, felixbrunnegard commented on src/main/java/com/TDA367group15/app/GameLoop.java
> +     * @return
Borde stå vad den returnar här

2022-10-24 08:08 UTC, Annelie12 commented on src/main/java/com/TDA367group15/app/model/Player.java
> -
nejdå den metoden används inte alls och allt funkar som det ska

2022-10-24 12:10 UTC, MaxSE21 approved these changes
seems good

2022-10-24 12:12 UTC, felixbrunnegard approved these changes

2022-10-24 12:13 UTC, merged